name: "Feature request"
description: Suggest an idea for this project
labels: enhancement
body:

- type: textarea
  attributes:
    label: 1
    description: Please list out the steps to reproduce your bug.
    placeholder: |
      1. Go to '...'
      2. Click on '....'
      3. Scroll down to '....'
      4. See error
  validations:
    required: true

- type: textarea
  attributes:
    label: 2
    description: Please list out the steps to reproduce your bug.
    placeholder: |
      1. Go to '...'
      2. Click on '....'
      3. Scroll down to '....'
      4. See error
  validations:
    required: true
    
- type: textarea
  attributes:
    label: 3
    description: Please list out the steps to reproduce your bug.
    placeholder: |
      1. Go to '...'
      2. Click on '....'
      3. Scroll down to '....'
      4. See error
  validations:
    required: true

- type: textarea
  attributes:
    label: 4
    description: Please list out the steps to reproduce your bug.
    placeholder: |
      1. Go to '...'
      2. Click on '....'
      3. Scroll down to '....'
      4. See error
  validations:
    required: true
