name: "Feature request"
description: Suggest an idea for this project
labels: enhancement
body:

- type: textarea
  attributes:
    label: Is your feature request related to a problem? Please describe.
    description: Please list out the steps to reproduce your bug.
    placeholder: |
      1. Go to '...'
      2. Click on '....'
      3. Scroll down to '....'
      4. See error
  validations:
    required: true

- type: textarea
  attributes:
    label: "Describe the solution you'd like"
    description: "Describe the solution you'd like"
    placeholder: |
      1. Go to '...'
      2. Click on '....'
      3. Scroll down to '....'
      4. See error
  validations:
    required: true
    
- type: textarea
  attributes:
    label: "Describe alternatives you've considered".
    description: "Describe alternatives you've considered".
    placeholder: |
      1. Go to '...'
      2. Click on '....'
      3. Scroll down to '....'
      4. See error
  validations:
    required: true

- type: textarea
  attributes:
    label: Additional context
    description: Please list out the steps to reproduce your bug.
    placeholder: |
      1. Go to '...'
      2. Click on '....'
      3. Scroll down to '....'
      4. See error
  validations:
    required: true
